#!/usr/bin/env python

import sys

if len(sys.argv) < 2:
    print('please specify the file')

path = sys.argv[1]
if not path.endswith('toml'):
    print('only support *.toml file')

with open(path) as f:
    print(f)
